replicaCount: 1

image:
  repository: anushrigarg9/go-web-app
  pullPolicy: IfNotPresent
  tag: "23087952541"

ingress:
  enabled: false
  className: ""
  annotations: {}

  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific